package dev.s3tupw1zard.gearMastery.stat;

public enum StatType {
    ATTACK_DAMAGE, ATTACK_SPEED, DURABILITY, MINING_SPEED, KNOCKBACK,
    PROJECTILE_DAMAGE, ARMOR, ARMOR_TOUGHNESS, KNOCKBACK_RESISTANCE,
    FISHING_LUCK, FISHING_SPEED
}
